// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF71x2vHPe4yBUR4IKrO9GmlmjV1PwE4E',
    appId: '1:932614966245:android:1bcb780c0ca45419a7fd0c',
    messagingSenderId: '932614966245',
    projectId: 'friend-ship-chat',
    storageBucket: 'friend-ship-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8mF1MxeNK53wSsYhqxMTFlwHGZoCvq_g',
    appId: '1:932614966245:ios:f3c013d83b360deea7fd0c',
    messagingSenderId: '932614966245',
    projectId: 'friend-ship-chat',
    storageBucket: 'friend-ship-chat.appspot.com',
    androidClientId: '932614966245-7uvju5m423og5a23djf0n39a1jamber9.apps.googleusercontent.com',
    iosClientId: '932614966245-7aqhan793rd3cul6usi0gv82g4u5cdhi.apps.googleusercontent.com',
    iosBundleId: 'com.example.friendShip',
  );
}
